### PR TITLE
Added fallbackTo404 response 

### PR DESCRIPTION
**Pull request by louiealmeda**
**Parent issue** 

Closes https://github.com/mockoon/mockoon/issues/473

**Technical implementation details**

* Added default values for fallbackTo404
* Updated routeResponse to return 404 if file is not found and fallbackTo404 is true

### CODE REVIEW

**Review by 255kb — CHANGES_REQUESTED** [review]
@louiealmeda Thanks for the PR.
I released `commons@2.4.0`, you can now use it in this package. 
There is one issue concerning the current implementation. Doing a `response.sendStatus(404)` will close the connection and send a 404 status, but the rest of the code will still get executed and result in the following two errors:
- `[SERVICE][SERVER]Error while serving the file content: Cannot read property 'toString' of undefined`
- `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

This could be solved by returning from the callback. 
But something else bothers me. Using `sendStatus(404)` will not only set the 404 status, but also send `text/plain` as Content-Type and set the body to "Not found". I feel like that this option should only override the status code and that we should revert to what has been set up in the route for the rest of the response (i.e. use the body editor content + the headers that are present). What do you think? Doing this would indirectly solve the bug above. 
It would require a little bit of refactoring. 
I am happy to take it from here if you want and also add the UI tests in the main app. Let me know.

**Comment by louiealmeda** [comment]
Hi @255kb, thanks for reviewing my PR and providing detailed feedback. Sorry for the late revert.. 
I'll try your suggestions within the week, I'll let you know if I get into any issues.

Thank you.

**Comment by 255kb** [comment]
> Hi @255kb, thanks for reviewing my PR and providing detailed feedback. Sorry for the late revert..
> I'll try your suggestions within the week, I'll let you know if I get into any issues.
> 
> Thank you.

No problem, 
For your information, I have to publish the next release before mid August (for certificates renewal reasons 😒). Your change still have a bit of time to be included.

**Comment by louiealmeda** [comment]
Hi @255kb, 

I've pushed my latest changes, i hope these are not too late..
So what I did was to keep the headers and other settings intact when it is falling back to use 404 status. It will use the body content in the editor as well if the file is not present, and process the templating if it's turned on.

> I am happy to take it from here if you want and also add the UI tests in the main app. Let me know.

I hope that the commons-server is good to go. For the main app, yes please I would need help on this part. As I might not be able to commit time within the coming weeks... Thank you so much! :)

**Review by 255kb — APPROVED** [review]
Thanks for the update @louiealmeda 
One thing I noticed is that falling back to the body in the editor was serving it without parsing the templating. So I refactored a bit (also to make the code more readable, thing that I wanted to do since a long time) to reuse the same code than when we don't serve a file. I will write the tests so it can be in the next release.

**Comment by louiealmeda** [comment]
Thank you for looking into it @255kb, I agree on the refactoring note. 👍

**Pull request merged**
